name: Build and publish docker image

# TODO: build and publish images on tags rather than every commit to master

on:
  push:
    branches: [ main ]

env:
  IMAGE_NAME: discoverrewind

jobs:
  build:
    name: Push Docker image to GitHub Container Registry
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build -t $IMAGE_NAME .

      - name: Authenticate into GitHub Container Registry
        run: echo "${{ secrets.GCR_TOKEN }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Tag and push image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository }}
          VERSION=${GITHUB_SHA}

          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
